server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    url: jdbc:h2:mem:test #配置h2数据库的连接地址
    username: sa
    password: sa
  h2:
    console:
      enabled: true #开启web console功能
# EasyProperties
easy:
  dictBeanPackage: com.easy.demo.dict,com.easy.demo.entity
  fileUrlPrefix: http://localhost:8080
  dictSwaggerSupport: true
  #下面四个可以不配置,目前配置的就是默认值
  fileFieldPrefix: full
  fileFieldSuffix:
  enumFieldPrefix:
  enumFieldSuffix: Label
  dictFieldPrefix:
  dictFieldSuffix: Label
